name: Package exe with PyInstaller - Windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/**

jobs:
  build_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
    - name: release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        name: ${{ steps.tag.outputs.new_tag  }}
        tag_name: ${{ steps.tag.outputs.new_tag }}
        files: |
          src/dist/windows/palworld-worldoptions.exe
      env:
        GITHUB_TOKEN: ${{ github.token }}